apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-token-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vault-token-sa-binding
  namespace: secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-token-sa
  namespace: secret
