{{- if .Values.Vault.Ingress.Enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "vault.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "vault.chart" . }}
    component: "{{ .Release.Name }}-{{ .Values.Vault.ComponentName }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{.Values.Vault.Tls.ServerName}}
    secretName: "{{ template "vault.fullname" . }}.tls"
  rules:
    - host: {{.Values.Vault.Tls.ServerName}}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ template "vault.fullname" . }}
            servicePort: {{.Values.Vault.HttpPort}}
{{- end }}
