apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-{{.Values.Vault.ComponentName}}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{.Values.Vault.ComponentName}}
    app: {{ template "name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  {{- if not .Values.Vault.Ingress.Enabled }}
  type: NodePort
  {{-  end }}
  ports:
  - name: https
    port: {{.Values.Vault.HttpPort}}
    {{- if not .Values.Vault.Ingress.Enabled }}
    nodePort: {{.Values.Vault.NodePort}}
    {{- end }}
  selector:
    release: {{ .Release.Name }}
    component: {{.Values.Vault.ComponentName}}
